# Config file for Spectroradiometer file extraction pipeline 
workingDir: C:/Users/André/OneDrive - CNR/Ricerca/Codice/Pipeline_spectroradiometer/Spettri 2026_Mar_24 IsCannoneris
destSubDir: out
spectralEvolutionMetaData:
    - Date
    - Time
    - Version
    - File Name
    - Instrument
    - Averages
    - Foreoptic
    - Radiometric Calibration
    - Channels
outputFile: out.xlsx
areaUserIdRegEx: "^[^[:blank:]]*"
planUserIdRegEx: "[^[:blank:]]*$"
treatmentUserIdRegEx:
genotypeUserIdRegEx:
